import x"$REPO_ROOT/source/modules/raiment-devenv/build/common.justfile"

CWD := shell('pwd')

#==============================================================================
# default
#==============================================================================

[private]
default:
    @just --list --unsorted

#==============================================================================
# ensure
#==============================================================================

ensure:
    @just ensure-build-directory


dev:
    watchexec \
        --watch src \
        --exts rs,toml,yaml \
        --restart \
        "just run && sleep 1"


build: 
    cargo build

test:
    echo "TODO"

run:
    cargo run