import "../../common/common.justfile"

ensure: ensure-build-directory
    @cd ${REPO_ROOT}/source/assets && just build

build: ensure
    cargo build --release

dev: ensure
    cargo run --release

dev-build:
    cargo watch -x 'build --release'

run: ensure lint
    cargo run --release

test: ensure
    cargo test

lint: build
    cargo clippy --fix --allow-dirty --allow-staged

clean:

