SCRIPTS := "${REPO_ROOT}/source/scripts"
EXPANDED := "${REPO_ROOT}/extern/expanded"
REPO_ROOT := "${REPO_ROOT}"

ensure:
    mkdir -p ./base/textures
    mkdir -p ./base/sprites

build: ensure
    cd ${REPO_ROOT}/extern && just expand
    @just build-tiny-textures
    @just build-content

[private]
build-tiny-textures:
    build/build-tiny-textures.ts

build-content:
    build/build-content.ts

clean:
    git clean -fdX ./base
